name: FlashcardMaker
dependencies:
  - appdirs==1.4.4
  - beautifulsoup4==4.11.1
  - brotlipy==0.7.0
  - bs4==0.0.1
  - cached-property==1.5.2
  - certifi==2022.5.18.1
  - cffi==1.15.0
  - charset-normalizer==2.0.4
  - chevron==0.14.0
  - cryptography==36.0.0
  - cssselect==1.1.0
  - decorator==5.1.1
  - fake-useragent==0.1.11
  - frozendict==2.3.2
  - genanki==0.13.0
  - idna==3.3
  - importlib-metadata==4.11.3
  - lxml==4.8.0
  - Markdown==3.3.6
  - orjson==3.6.8
  - parse==1.19.0
  - pip==21.2.4
  - protobuf==3.20.1
  - psutil==5.8.0
  - pycparser==2.21
  - pyee==8.2.2
  - pyOpenSSL==22.0.0
  - pyppeteer==1.0.2
  - pyquery==1.4.3
  - PySocks==1.7.1
  - python-dateutil==2.8.2
  - PyYAML==6.0
  - requests==2.27.1
  - requests-html==0.10.0
  - setuptools==61.2.0
  - six==1.16.0
  - soupsieve==2.3.1
  - tqdm==4.64.0
  - urllib3==1.26.9
  - w3lib==1.22.0
  - websockets==10.3
  - wheel==0.37.1
  - zipp==3.8.0
