name: FlashcardMaker
channels:
  - defaults
dependencies:
  - pip
  - bzip2
  - ca-certificates
  - charset-normalizer
  - icu
  - idna
  - libcxx
  - libffi
  - libiconv
  - libxml2
  - libxslt
  - ncurses
  - openssl
  - pycparser
  - python=3.10
  - readline
  - requests
  - soupsieve
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
    - appdirs
    - beautifulsoup4
    - brotlipy
    - bs4
    - cached-property
    - certifi
    - cffi
    - chevron
    - cryptography
    - cssselect
    - decorator
    - deepl
    - fake-useragent
    - frozendict
    - genanki
    - importlib-metadata
    - lxml
    - markdown
    - orjson
    - parse
    - pip
    - protobuf
    - psutil
    - pyee
    - pyppeteer
    - pyquery
    - pysocks
    - python-dateutil
    - pyyaml
    - requests-html
    - setuptools
    - six
    - tqdm
    - urllib3
    - w3lib
    - websockets
    - zipp